name: Docker Image CI

on:
  push:
    branches: [ armv7 ]
  pull_request:
    branches: [ armv7 ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * *'
    
env:
  ALPINE_VERSION: 3.15    

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag gounthar/alpine-linux-curl
        docker build . --file Dockerfile --tag gounthar/alpine-linux-curl:$ALPINE_VERSION
        docker push gounthar/alpine-linux-curl
        docker push gounthar/alpine-linux-curl:$ALPINE_VERSION
